spring.application.name=basketball-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/basketball
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.sms.development-mode=true
